export const group02 = [
  {
    id: "list0066",
    img: "/manzashops/assets/cover1.png",
    name: "Pete Biz Mark",
    rate: "45.00",
    profession: "graphic design",
    rating: "Great!",
    links: [
      {
        id: "link0001",
        img: "/manzashops/assets/facebook.png",
        alt: "facebook",
        href: "",
      },
      {
        id: "link0002",
        img: "/manzashops/assets/portfolio.jpg",
        alt: "portfolio",
        href: "",
      },
      {
        id: "link0003",
        img: "/manzashops/assets/instagram.png",
        alt: "instagram",
        href: "",
      },
      {
        id: "link0004",
        img: "/manzashops/assets/github.png",
        alt: "github",
        href: "",
      },
      {
        id: "link0005",
        img: "/manzashops/assets/YouTube.png",
        alt: "YouTube",
        href: "",
      },
    ],
  },
  {
    id: "list0067",
    img: "/manzashops/assets/cover1.png",
    name: "Pete Biz Mark",
    rate: "45.00",
    profession: "graphic design",
    rating: "Great!",
    links: [
      {
        id: "link0001",
        img: "/manzashops/assets/facebook.png",
        alt: "facebook",
        href: "",
      },
      {
        id: "link0002",
        img: "/manzashops/assets/portfolio.jpg",
        alt: "portfolio",
        href: "",
      },
      {
        id: "link0003",
        img: "/manzashops/assets/instagram.png",
        alt: "instagram",
        href: "",
      },
      {
        id: "link0004",
        img: "/manzashops/assets/github.png",
        alt: "github",
        href: "",
      },
      {
        id: "link0005",
        img: "/manzashops/assets/YouTube.png",
        alt: "YouTube",
        href: "",
      },
    ],
  },
  {
    id: "list0068",
    img: "/manzashops/assets/cover1.png",
    name: "Pete Biz Mark",
    rate: "45.00",
    profession: "graphic design",
    rating: "Great!",
    links: [
      {
        id: "link0001",
        img: "/manzashops/assets/facebook.png",
        alt: "facebook",
        href: "",
      },
      {
        id: "link0002",
        img: "/manzashops/assets/portfolio.jpg",
        alt: "portfolio",
        href: "",
      },
      {
        id: "link0003",
        img: "/manzashops/assets/instagram.png",
        alt: "instagram",
        href: "",
      },
      {
        id: "link0004",
        img: "/manzashops/assets/github.png",
        alt: "github",
        href: "",
      },
      {
        id: "link0005",
        img: "/manzashops/assets/YouTube.png",
        alt: "YouTube",
        href: "",
      },
    ],
  },
  {
    id: "list0069",
    img: "/manzashops/assets/cover1.png",
    name: "Pete Biz Mark",
    rate: "45.00",
    profession: "graphic design",
    rating: "Great!",
    links: [
      {
        id: "link0001",
        img: "/manzashops/assets/facebook.png",
        alt: "facebook",
        href: "",
      },
      {
        id: "link0002",
        img: "/manzashops/assets/portfolio.jpg",
        alt: "portfolio",
        href: "",
      },
      {
        id: "link0003",
        img: "/manzashops/assets/instagram.png",
        alt: "instagram",
        href: "",
      },
      {
        id: "link0004",
        img: "/manzashops/assets/github.png",
        alt: "github",
        href: "",
      },
      {
        id: "link0005",
        img: "/manzashops/assets/YouTube.png",
        alt: "YouTube",
        href: "",
      },
    ],
  },
  {
    id: "list0070",
    img: "/manzashops/assets/cover1.png",
    name: "Pete Biz Mark",
    rate: "45.00",
    profession: "graphic design",
    rating: "Great!",
    links: [
      {
        id: "link0001",
        img: "/manzashops/assets/facebook.png",
        alt: "facebook",
        href: "",
      },
      {
        id: "link0002",
        img: "/manzashops/assets/portfolio.jpg",
        alt: "portfolio",
        href: "",
      },
      {
        id: "link0003",
        img: "/manzashops/assets/instagram.png",
        alt: "instagram",
        href: "",
      },
      {
        id: "link0004",
        img: "/manzashops/assets/github.png",
        alt: "github",
        href: "",
      },
      {
        id: "link0005",
        img: "/manzashops/assets/YouTube.png",
        alt: "YouTube",
        href: "",
      },
    ],
  },
];
