export const group02 = [
  {
    id: "prod0007",
    title: "",
    href: "https://www.abercrombie.com/shop/us/p/cropped-dressy-zip-jacket-56312330?categoryId=12221&faceout=model&seq=06&afsource=social+proofing/",
    img: "/manzashops/assets/abercrombie/aberj1.avif",
    name: "crop dressy jacket",
    price: "150.00",
    description:
      "Sleek and stylish, this piece offers comfort and timeless appeal.",
  },
  {
    id: "prod0008",
    title: "",
    href: "https://www.abercrombie.com/shop/us/p/floral-sherpa-zip-trucker-jacket-57732339?categoryId=12221&faceout=model&seq=01/",
    img: "/manzashops/assets/abercrombie/aberj2.avif",
    name: "flora Trucker jacket",
    price: "112.00",
    description: "Crafted for durability and everyday elegance in one package.",
  },
  {
    id: "prod0009",
    title: "",
    href: "https://www.abercrombie.com/shop/us/p/cropped-vegan-leather-zip-trucker-jacket-57520355?categoryId=12221&faceout=model&seq=01&afsource=social+proofing/",
    img: "/manzashops/assets/abercrombie/aberj3.avif",
    name: "Elegant Fit",
    price: "55.00",
    description: "Modern design meets practicality for effortless wear.",
  },
  {
    id: "prod0010",
    title: "",
    href: "/",
    img: "/manzashops/assets/abercrombie/aberj4.avif",
    name: "Active Wear",
    price: "75.00",
    description: "Lightweight and versatile, perfect for any occasion.",
  },
  {
    id: "prod0011",
    title: "",
    href: "/",
    img: "/manzashops/assets/abercrombie/aberj5.avif",
    name: "crop zip jacket",
    price: "150.00",
    description: "Simple yet bold, designed for comfort and style.",
  },
  {
    id: "prod0012",
    title: "",
    href: "/",
    img: "/manzashops/assets/abercrombie/aberj6.avif",
    name: "steelers bomber jacket",
    price: "220.00",
    description: "A classic choice, blending quality with sophistication.",
  },
];
