export const group02 = [
  {
    id: "prod0007",
    title: "Hooded Sweatshirt",
    href: "/",
    img: "/manzashops/assets/jeans/new2.jpeg",
    name: "Cozy Fleece Hoodie",
    price: "45.00",
    description:
      "Sleek and stylish, this piece offers comfort and timeless appeal.",
  },
  {
    id: "prod0008",
    title: "Puffer Jacket",
    href: "/",
    img: "/manzashops/assets/jeans/new4.jpeg",
    name: "Winter Essential",
    price: "100.00",
    description: "Crafted for durability and everyday elegance in one package.",
  },
  {
    id: "prod0009",
    title: "Slim Trousers",
    href: "/",
    img: "/manzashops/assets/jeans/new3.jpeg",
    name: "Elegant Fit",
    price: "55.00",
    description: "Modern design meets practicality for effortless wear.",
  },
  {
    id: "prod0010",
    title: "Sports Sneakers",
    href: "/",
    img: "/manzashops/assets/jeans/style.jpeg",
    name: "Active Wear",
    price: "75.00",
    description: "Lightweight and versatile, perfect for any occasion.",
  },
  {
    id: "prod0011",
    title: "Trench Coat",
    href: "/",
    img: "/manzashops/assets/jeans/style4.jpeg",
    name: "Timeless Outerwear",
    price: "150.00",
    description: "Simple yet bold, designed for comfort and style.",
  },
  {
    id: "prod0012",
    title: "Casual Polo",
    href: "/",
    img: "/manzashops/assets/jeans/style5.jpeg",
    name: "Everyday Comfort",
    price: "35.00",
    description: "A classic choice, blending quality with sophistication.",
  },
];
